# Schema for the configuration files of the Code Enigma LDAP module.
ce_ldap.settings:
  type: config_object
  label: 'Code Enigma LDAP settings'
  mapping:
    group_commonname:
      type: string
      label: 'Group Common Name'
    group_base:
      type: string
      label: 'Group Base'
    people_base:
      type: string
      label: 'People Base'
    get_all_groups_filter:
      type: string
      label: 'Get All Groups Filter'
    admin_group_filter:
      type: string
      label: 'Admin Group Filter'
    excluded_admin_groups_for_user:
      type: string
      label: 'Excluded Admin Groups for User'
